### ISSUE TITLE
looks like an exception is being thrown

### ISSUE THREAD

**Issue by awinner1** [gnur/demeter#11]
just started using demeter, add a few host, and started a scrape run, and get this. deleted the DB and retried and it happens again, so is reproducible. As a side note I'm running in WSL Ubuntu, so that might be a factor.  cut and paste of CLI follows:

root@041-WINNA-Q46Y2:/mnt/e/tools/demeter# ./demeter scrape run -d /mnt/e/media/ebooks
INFO[2019-12-11T07:18:54-08:00] Starting work                                 host="http://174.105.111.217:8080"
INFO[2019-12-11T07:18:54-08:00] Starting work                                 host="http://98.209.96.49:8080"
INFO[2019-12-11T07:18:54-08:00] Starting work                                 host="http://67.1.213.77:8080"
INFO[2019-12-11T07:18:54-08:00] Starting work                                 host="http://185.215.227.81:8081"
INFO[2019-12-11T07:18:54-08:00] Starting work                                 host="http://24.253.114.187:8081"
ERRO[2019-12-11T07:18:55-08:00] Scraping failed                               err="Get http://185.215.227.81:8081/ajax/search?num=0: dial tcp 185.215.227.81:8081: connect: connection refused" host="http://185.215.227.81:8081"
ERRO[2019-12-11T07:18:55-08:00] Scraping failed                               err="Get http://24.253.114.187:8081/ajax/search?num=0: dial tcp 24.253.114.187:8081: connect: connection refused" host="http://24.253.114.187:8081"
INFO[2019-12-11T07:18:59-08:00] Found results                                 host="http://174.105.111.217:8080" new=229 total=229
panic: cannot free page 0 or 1: 0

goroutine 997 [running]:
go.etcd.io/bbolt.(*freelist).free(0xc0000955f0, 0x283, 0x7f88cd900000)
        /Users/erwindk/go/pkg/mod/go.etcd.io/bbolt@v1.3.0/freelist.go:109 +0x336
go.etcd.io/bbolt.(*Tx).Commit(0xc00048c000, 0x0, 0x0)
        /Users/erwindk/go/pkg/mod/go.etcd.io/bbolt@v1.3.0/tx.go:176 +0x1b7
go.etcd.io/bbolt.(*DB).Update(0xc00000a1e0, 0xc0003d8f28, 0x0, 0x0)
        /Users/erwindk/go/pkg/mod/go.etcd.io/bbolt@v1.3.0/db.go:602 +0xe8
go.etcd.io/bbolt.(*batch).run(0xc0001a0880)
        /Users/erwindk/go/pkg/mod/go.etcd.io/bbolt@v1.3.0/db.go:714 +0x11c
sync.(*Once).Do(0xc0001a0890, 0xc00004e7a8)
        /usr/local/Cellar/go/1.12.6/libexec/src/sync/once.go:44 +0xb3
go.etcd.io/bbolt.(*batch).trigger(0xc0001a0880)
        /Users/erwindk/go/pkg/mod/go.etcd.io/bbolt@v1.3.0/db.go:696 +0x54
created by time.goFunc
        /usr/local/Cellar/go/1.12.6/libexec/src/time/sleep.go:169 +0x44
root@041-WINNA-Q46Y2:/mnt/e/tools/demeter#

**Comment by awinner1** [comment]
let me know if I can help debug, even willing to go to source, though I'm good at Python, never tried Go.

**Comment by gnur** [comment]
I've just made a new release with a new go version and updated dependencies, can you confirm if it still happens?
