### ISSUE TITLE
Add Option for Rate Limiting Downloads

### ISSUE THREAD

**Issue by ForestFeather** [gnur/demeter#12]
It would be nice to have an option to specify maximum download rate and such.  I do my work remotely and if I'm downloading from something and trying to remote in it severely lags my connection and can sometimes disconnect - but if it could be limited to say, 50kb/s as an example, that would make things a lot easier.  Thank you!

**Comment by gnur** [comment]
As of now it would be quite complicated to implement.  

There are multiple workers working at the same time, you could limit the amount of workers to a single one with `scrape run -w 1` to limit the work being done.
