### ISSUE TITLE
Allow different format options (epub, pdf, mobi, etc)

### ISSUE THREAD

**Issue by sean-public** [gnur/demeter#3]
I prefer `mobi` over `epub`, it would be handy for people to use a command-line parameter to select which they prefer for when you pull the path from the JSON object here:

https://github.com/gnur/demeter/blob/9995d58d19ea08c4f96603e9da7e95230ecb536b/lib/functions.go#L358

**Comment by gnur** [comment]
Good idea, I'll make a flag for it

**Comment by phhowe17** [comment]
Could you allow for multiple options? e.g. -f epub, mobi  or -f epub -f mobi ?

**Comment by dpieski** [comment]
And/or maybe an optional strict determination of whether the book is already in the library to include the format.

so strict matching: dune.epub =/= dune.pdf
non-strict: dune.epub == dune.pdf

Or maybe a preference order somehow to download epub over mobi and mobi over pdf for the same title/author combo. 

so: have mobi, find pdf - don't download.
but: have mobi, find epub - do download
