### ISSUE TITLE
err="invalid character '<' looking for beginning of value" host="http://something:8083"

### ISSUE THREAD

**Issue by thisadamis** [gnur/demeter#4]
I get this when i run demeter scrape run -d books after adding the host.

Any ideas?

**Comment by Wingysam** [comment]
Is the host still running a calibre library?

**Comment by thisadamis** [comment]
yup http://92.246.18.172:8083/

**Comment by Wingysam** [comment]
That's Calibre-web, not Calibre. You can't use this tool to download those. Sorry, I don't know any that can. Maybe wget?

**Comment by thisadamis** [comment]
ahhhh ok thx
